#!/bin/sh
if [ "$SKIP_PRECOMMIT" = "true" ]; then
  echo "Skipping pre-commit hook"
  bun run loc
  exit 0
fi

if [ "$CI_TEST" = "true" ]; then
  echo "Testing CI"
  bun run test:ci
fi

bun run test:build
bun run loc
