#!/bin/sh
if [ "$SKIP_PRECOMMIT" = "true" ]; then
  echo "Skipping pre-commit build test"
  cd src-tauri
  cargo clean
  cd ..

  bun run format
  bun run lint
  bun run loc
  exit 0
fi

if [ "$CI_TEST" = "true" ]; then
  echo "Testing CI"
  bun run test:ci
fi

bun run test:build

rm -rf dist

cd src-tauri
cargo clean
cd ..
bun run format
bun run lint

bun run loc
